# Generated by Django 3.1 on 2021-06-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oxygen_Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('Business_Name', models.CharField(max_length=30)),
                ('Person_Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=12)),
                ('Verified_Status', models.CharField(max_length=30)),
                ('TimeStamp', models.CharField(max_length=30)),
            ],
        ),
    ]
