# Generated by Django 3.1 on 2021-06-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oxygen_leads',
            name='TimeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
